### ISSUE TITLE
input mismatch of loss predictor

### ISSUE THREAD

**Issue by jordane95** [Haochen-Wang409/HPM#1]
Hi,

Very interesting paper. I have a question regarding the implementation.

In your paper, the teacher model predicts loss for each patch based on fully visible image, while the student model learns to predict masked patch loss based on the unmasked patches. Is there a mismatch during training and inference of loss predictor?

**Comment by Haochen-Wang409** [comment]
Thanks for your attention to our work!
Yes, you are right. There might be some discrepancies, but we empirically found that patches with higher predicted loss tend to be more discriminative (see Fig. 2, Fig. S1, and Fig. S2).
Revisiting this mismatch can be interesting for future works.

**Comment by jordane95** [comment]
Thanks for your reply!

Another question: Why bother to learn an additional decoder for loss prediction? Why don't you just use the original loss of reconstruction decoder from the teacher model for hard patch mining?

**Comment by Haochen-Wang409** [comment]
There is no reconstruction loss if we take fully visible images as input.
