### ISSUE TITLE
Confused about "model_teacher" in pre-training code

### ISSUE THREAD

**Issue by Sreyan88** [Haochen-Wang409/HPM#4]
Hello,

Thank You for your great work. I was going through `main_pretrain.py` and figured out you have three models, `model_teacher`, `model`, and `model_ema`. From your paper I understand, you have 2 models that takes part in the pre-training process, one model (the `model`?) and the other an ema-based model (the `model_ema`?). Thus, my question is, what role is the `model_teacher` playing?

Thank You!

**Comment by Haochen-Wang409** [comment]
Hello, thanks for your attention.

In fact, ```model_teacher``` is only used in Tab. 1 and Tab. 5 when studying the effectiveness of different reconstruction targets. For instance, if we want to reconstruct CLIP features, then ```model_teacher``` should be the pre-trained CLIP model and it is frozen during training.
By default, HPM takes raw RGB pixels as reconstruction targets, and thus ```model_teacher``` is never be used.

**Comment by Sreyan88** [comment]
Thank You for your reply!
