### ISSUE TITLE
Questions Regarding Pretraining Experiment Configuration

### ISSUE THREAD

**Issue by barry-wy** [Haochen-Wang409/HPM#6]
I have some inquiries regarding the pretraining experiment configuration with imagenet1k for the HPM project and would appreciate obtaining more detailed information about this experiment to better understand the project's performance and resource requirements.

1.How many GPUs were used during pretraining？
2.Please provide detailed information about the GPU models or specifications used for pretraining.
3.What was the total training time for pretraining？
4.What was the GPU memory consumption per card during pretraining?

**Comment by Haochen-Wang409** [comment]
Thanks for your attention to our HPM.

1 & 2. We use 64 2080Ti GPUs for pre-training.
3. It takes around 2 days for 200 epochs of pre-training.
4. About 9 GB.
