### ISSUE TITLE
Availability of Pre-trained Models

### ISSUE THREAD

**Issue by FangHeng** [Haochen-Wang409/HPM#8]
I am interested in your project and I am keen on experimenting with it for my research. I was wondering if you have any plans to provide pre-trained models that users can directly use without going through the training process themselves. Having access to pre-trained models can help in significantly reducing the time and resources required to get started with the project.

Thank you for considering this request. Looking forward to your response.

**Comment by VisDrone** [comment]
Have you found the pre-training weights? The author seems to have only released the finetuned weights.
